name: 'screenshot-url'
description: 'Take a screenshot of a URL'
inputs:
  url:
    description: 'URL to screenshot'
    required: true
outputs:
  screenshot_path: # output will be available to future steps
    description: 'The filesystem path to the generated screenshot'
runs:
  using: 'node12'
  main: 'dist/index.js'
