name: Screenshot

on:
  push

jobs:
  screenshot:
    name: Screenshot
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout
      uses: actions/checkout@v1.0.0

    - name: Capture Screenshot
      id: screenshot
      uses: ./
      with:
        source: https://github.com/swinton
        destination: github-com-swinton-${{ matrix.os }}.png
